# Use the Go base image
FROM golang:1.20 AS builder

# Set the working directory
WORKDIR /app

# Copy the go.mod and go.sum files
COPY go.mod go.sum ./

# Download the Go modules
RUN go mod download

# Copy the source code
COPY . .

# Build the Go application
RUN go build -o main .

# Use a smaller base image for the final stage
FROM gcr.io/distroless/base

# Copy the built binary
COPY --from=builder /app/main .

# Expose port 8080
EXPOSE 8080

# Run the binary
ENTRYPOINT ["/main"]
